name: ci
run-name: "Build and Test for ${{ github.ref_name }} by ${{ github.actor }}"
on: # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json

      # ===== Frontend =====
      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: frontend

      # Could be removed
      - run: npm run build
        working-directory: frontend

      - run: npm run lint
        working-directory: frontend

      - run: npm audit --audit-level=moderate
        working-directory: frontend

      # # ===== Backend =====
      # - name: Install Backend Dependencies
      #   run: npm ci
      #   working-directory: backend

      # - run: npm run build --if-present
      #   working-directory: backend

      # - run: npm run lint
      #   working-directory: backend

      # - run: npm audit --audit-level=moderate
      #   working-directory: backend
